repositories:
  - name: fluxcd
    url: https://charts.fluxcd.io

releases:
  # https://github.com/fluxcd/flux/blob/master/chart/flux/README.md
  - name: flux
    namespace: flux
    chart: fluxcd/flux
    values:
      - git:
          url: git@github.com:int128/continuous-deployment-flux-demo
          path: manifests
          pollInterval: 1m
        registry:
          includeImage: gcr.io/int128-1313/github.com/int128/hellopage
          automationInterval: 1m
