repositories:
  - name: fluxcd
    url: https://charts.fluxcd.io

releases:
  - name: flux
    namespace: flux
    chart: fluxcd/flux
    values:
      - git:
          url: git@github.com:int128/continuous-deployment-flux-demo
          path: manifests
          pollInterval: 1m
        registry:
          automationInterval: 1m
